language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

branches:
  only:
    - master

# Travis is running Ubuntu 14.04 which doesn't have package libbase58
before_install:
  - wget https://github.com/bitcoin/libbase58/archive/v0.1.4.tar.gz -O libbase58-0.1.4.tar.gz
  - tar -xzf libbase58-0.1.4.tar.gz
  - pushd libbase58-0.1.4 && autoreconf --install && ./configure --prefix=/usr && make && sudo make install && popd
  - test "$TRAVIS_PHP_VERSION" != "nightly" || export COMPOSER_FLAGS="$COMPOSER_FLAGS --ignore-platform-reqs"

install:
  - pecl install base58-beta
  - pecl install --soft sodium
  - composer install $COMPOSER_FLAGS
  - wget https://scrutinizer-ci.com/ocular.phar -O "$HOME/ocular.phar"

before_script: |
  if (php -m | grep -q -i xdebug); then
    export PHPUNIT_FLAGS="--coverage-clover cache/logs/clover.xml"
  else
    export PHPUNIT_FLAGS="--no-coverage"
  fi

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS

after_success:
  - test "$PHPUNIT_FLAGS" == "--no-coverage" || php "$HOME/ocular.phar" code-coverage:upload --format=php-clover cache/logs/clover.xml
