language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

branches:
  only:
    - master

install:
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar -O "$HOME/ocular.phar"
  - pecl install base58

script:
  - vendor/bin/phpunit --coverage-clover cache/logs/clover.xml

after_success:
  - php "$HOME/ocular.phar" code-coverage:upload --format=php-clover cache/logs/clover.xml
